config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'archives', to: 'blogs#archives'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: {draft: 0 , published: 1}
  extend FriendlyId
  friendly_id :title , use: :slugged

  validates_presence_of :title, :body

  belongs_to :topic
  has_many :comments ,dependent: :destroy

  
  def self.archives archivedate    
    blogsbetweendates(archivedate)
  end

  def self.blogscount date
    blogsbetweendates(date).count  
  end

  def self.blogsbetweendates date
    start_date = date.to_date.at_beginning_of_month
    end_date = date.to_date.at_end_of_month
    where(:created_at => start_date..end_date)
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy,:toggle_status]
  layout "blog"
  access all: [:show,:index,:new ,:create ,:update ,:edit,:destroy] ,user:{except: [:toogle_status]},site_admin: :all

  # GET /blogs
  # GET /blogs.json
  def archives
    if  params[:date].nil?
       redirect_to blogs_url
    else
      @blogs = Blog.archives(params[:date])
    end    
  end

  def index
    @blogs = Blog.page(params[:page]).per(5)
  end

  # GET /blogs/1
  # GET /blogs/1.json
  def show
    @blog = Blog.includes(:comments).friendly.find(params[:id])
    @comment = Comment.new
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  # POST /blogs.json
  def create
    @blog = Blog.new(blog_params)
    @blog.topic = Topic.find(params[:blog][:topic_id])
    
    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1
  # PATCH/PUT /blogs/1.json
  def update
    debugger
    @blog.topic = Topic.find(params[:blog][:topic_id]) 
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1
  # DELETE /blogs/1.json
  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end      
    redirect_to blogs_url,notice: 'Post status has been updated' 
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blog
      #params[:id] = my-blog-post-3
      # Blog.where(slug:params[:id])
      @blog = Blog.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def blog_params
      params.require(:blog).permit(:title,:body,:topic_id)
    end

    def archives_params
      params.require(:archives).permit(:date)
    end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
  
  
    <p class="blog-post-meta">
    <% if current_user.is_a?(GuestUser) %>  
    
    <% else %>
      <%= link_to 'Edit', edit_blog_path(blog) %>
      / <%= link_to blog.status, toggle_status_blog_path(blog) %> /
       <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } if logged_in?(:site_admin) %>
    <% end %>
    </p>
  

  <p>
    <%= blog.body %>
  </p>
</div>

app/views/blogs/_form.html.erb
<%= form_for(blog) do |f| %>
  <% if blog.errors.any? %>
    <% blog.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, class: 'form-control', rows: 5 %>
  </div>

  <div class="form-group">
    <%= f.select :topic_id , Topic.all.collect { |t| [ t.title , t.id ] },:prompt => 'Select Topic'%>
  </div>

  <%# render 'shared/dropdown' , object: @blog  %>

  <div class="form-group">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
  </div>
<%end%>

app/views/blogs/archives.html.erb
<div class="col-sm-8 blog-main">

  <%# paginate @blogs %>
  <%= render @blogs %>
  <%# paginate @blogs %>
</div>

app/views/blogs/edit.html.erb
<div class="col-sm-8 blog-main">

  <h1>Editing Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="col-sm-8 blog-main">
  
  <%= paginate @blogs %>
  <%= render partial: 'blog', collection: @blogs %>

  <%# render @blogs %>
  <%= paginate @blogs %>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-8 blog-main">
  <h1>New Blog</h1>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-8 blog-main">

  <h2><%= @blog.title %></h2>

  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>

  <p>
    <%= @blog.body %>
  </p>

  <%# render 'comments/comment_form' ,@blog.comments %>
  

  <div id="comments" data-blog-id="<%= @blog.id %>">
    <%# render @blog.comments %>
  </div>
</div>