config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'archives', to: 'blogs#archives'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  include Placeholder
  has_many :technologies , dependent: :delete_all
  accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
                                reject_if: lambda {|attr| attr['name'].blank?}
  #Portfolio.create!(title:"Web app",subtitle:"asdcdzc",body:"scdcf",
  #technologies_attributes:[{name: 'Ruby' },{name: 'Rails'},{name:'Icnoic'}])
  
  validates_presence_of :title , :body 

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  def self.by_position
    order("position ASC")
  end

  scope :ruby_on_rails_ang , -> {where(subtitle: "Angular")} 
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  layout 'portfolio' 
  before_action :set_portfolio_item,only: [:edit,:update,:show,:destroy ]
  access all: [:show,:index,:angular,:new ,:create ,:update ,:edit],user:{except: [:destroy,:sort]},site_admin: :all

  def index
    @portfolio_items = Portfolio.by_position
  end

  def sort
    params[:order].each do |key,value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end
    render nothing: true
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def show
    @portfolio_item = Portfolio.find(params[:id])  
  end

  def new
    @portfolio_item = Portfolio.new
    #it will instantiate 2 technologies into current version of portfolio_item object
    2.times { @portfolio_item.technologies.build }

  end

  def edit
    @portfolio_item = Portfolio.find(params[:id])
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Blog was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

    def update
      @portfolio_item = Portfolio.find(params[:id])
      respond_to do |format|
        if @portfolio_item.update(portfolio_params)
          format.html { redirect_to portfolios_path, notice: 'The record successfully updated.'}
        else
          format.html { render :edit}
        end
      end
    end

    def destroy
      @portfolio_item = Portfolio.find(params[:id])
      @portfolio_item.destroy
      respond_to do |format|
        format.html { redirect_to portfolios_url,notice: 'Record was deleted'}     
      end
    end

private
  def portfolio_params
      params.require(:portfolio).permit(:title,
                                        :subtitle,
                                        :body,
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id,:name,:destroy])
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end    
end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:,width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img img,type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350',width:'200')
    elsif type == 'main'
      image_generator(height: '600',width:'400')
    end
  end
end


  

   

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio_item) do |f| %>
  <% if @portfolio_item.errors.any? %>
    <% @portfolio_item.errors.full_messages.each do |error| %>
      <%= alert_generator error%>
    <% end %>
  <%end%>  

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>
  

      <div class="form-group">
        <label class = "btn btn-primary">
          Upload a main image <%= f.file_field :main_image,style: 'display:none;' %>    
        </label>
      </div>  
      
      <div class="form-group">
        <label class = "btn btn-primary">
          Upload a thumb image <%= f.file_field :thumb_image,style: 'display:none;' %>    
        </label>
      </div> 

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>
</div>

  <hr>

  <div class="col-md-12">
    <h2>Technolgies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields',f:technology_form %>
      <% end %>
      
      
    </div>

    <div class="form-group">
      <%= f.submit 'Save Portfolio Item', class: 'btn btn-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/portfolios/_portfolio_item.html.erb
<div class="card" data-id="<%= portfolio_item.id %>">
  <%# image_tag portfolio_img(portfolio_item.thumb_image,'thumb')  %>
  <p class="card-text">
    <span><%= link_to portfolio_item.title ,  portfolio_show_path(portfolio_item) %></span><br>
     <span><%= portfolio_item.subtitle %></span><br>
     <span><%= portfolio_item.body %></span>
  </p>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
</div>

app/views/portfolios/angular.html.erb
<h1>Portfolios Items</h1>

<%= link_to "Create new Item",new_portfolio_url%>

<table>
  <tr>
    <th>Title</th>
    <th>Subtitle</th>
    <th>Body </th>
    <th>Main_image</th>
  </tr>
   
   <% @angular_portfolio_items.each do |portfolio_item| %>
    <tr>
      <td><%= link_to portfolio_item.title,portfolio_show_url(portfolio_item) %></td>
      <td><%= portfolio_item.subtitle %></td>
      <td><%= portfolio_item.body %></td>
      <td><%= portfolio_item.main_image %></td>

      <td><%= link_to 'Edit', edit_portfolio_url(portfolio_item) %></td>
      <td><%= link_to 'Delete ',portfolio_path(portfolio_item),method: :delete , data: {confirm: 'Are you sure ?'} %></td>
    </tr>
  <% end %>
</table>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album text-muted">
  <div class="container">
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <%= render partial: 'portfolio_item', collection: @portfolio_items %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-container">
  <h1>Create a new Portfolio Item</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>  
</div>

app/views/portfolios/show.html.erb
<div class= "container portfolio-container">
  <div class = "row">
    <div class = "col-md-7">
      <%# image_tag portfolio_img(@portfolio_item.thumb_image,'main'),width: '100' %>
    </div>
    
    <div class = "col-md-5">
    <p>
      <strong>Title:</strong>
      <%= @portfolio_item.title %>
    </p>
   
    <p>
      <strong>Subtitile:</strong>
      <%= @portfolio_item.subtitle %>
    </p>

    <p>
      <strong>Body:</strong>
      <%= @portfolio_item.body %>
    </p>

    <h2>Technologies Used:</h2>

    <% @portfolio_item.technologies.each do |t| %>
    <p><%= t.name %></p>
    <%end%>

    <%if logged_in?(:site_admin)%>
      <div class = "">
        <%= link_to "Edit Item" , edit_portfolio_path(@portfolio_item) , class: 'btn btn-warning'%>
      </div>
    <% end %>
    
    </div>
  </div>
</div> 


  