config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end

  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'
  get 'archives', to: 'blogs#archives'

  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
      <div class="inner">
        <p class = "app-footer"><%= @copyright %></p>
      </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand"><%= current_user.name %></h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>Blog template built for <a href="https://getbootstrap.com">Bootstrap</a> by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
    <div class="container">
      <h1 class="blog-title">My Blog</h1>
      <% if current_user.is_a?(GuestUser) %>

      <% else %>
         <%= link_to 'Write a New Blog', new_blog_path  %>
      <% end %>
    </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
       <h3 class="masthead-brand" style = " margin-top: 8px;">
        <%= current_user.name %>    
      </h3>
         <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    
  </div>
  <div class="sidebar-module">
    <h4>Archives</h4>
    <ol class="list-unstyled">

      <% months.each do |m|%>
        <li><%=link_to m.strftime("%B"),{:controller => "blogs",:action => "archives",:date => m},:method=> :get%>
        (<%= blogscount(m) %>) </li>
      <%end%>

      <!-- <li><%#link_to prevmonth.strftime("%B"),{:controller => "blogs",:action => "archives",:date => prevmonth},:method=> :get%>
      (<%# blogcountlastmonth %>) </li> -->
      <!-- <li><a href="/archives"><%# Date.today.prev_month.strftime("%B")%> (<%# archivescount[0].count %>)</a></li>
      <li><a href="/archives"><%# Date.today.prev_month.prev_month.strftime("%B")%> (<%# archivescount[1].count %>)</a></li> -->      
    </ol>
  </div>

  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links">
      <li><a href="https://github.com/"><%= fa_icon "github" %></a></li>
      <li><a href="https://www.facebook.com/"><%= fa_icon "facebook" %></a></li>
      <li><a href="https://twitter.com/login"><%= fa_icon "twitter" %></a></li>
      <li><a href="https://www.instagram.com/"><%= fa_icon "instagram" %></a></li>
    </ol>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class= "<%= location %>">
<%= link_to "Home",root_path,class: "nav-link" %>
<%= link_to "About",about_path,class: "nav-link" %>
<%= link_to "Contact",contact_path,class: "nav-link"%>
<%= link_to "Blog",blogs_path ,class: 'nav-link' %>
<%= link_to "Portfolio",portfolios_path, class: 'nav-link'%>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "View All Portfolio Items", portfolios_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_nav.html.erb
<div class="portfolio-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <h3 style= "color: #f19916" ><%= current_user.name %></h3>
          <%= nav_helper 'nav-link', 'span' %>
          <%= login_helper 'nav-link' %>
    <div style="margin-top: 8px ; ">
        <%= link_to "New Portfolio" , new_portfolio_url %>
   </div>
    </nav>
  </div>
</div> 